# Generated by Django 4.1.3 on 2022-11-09 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_follower'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
