# Generated by Django 4.1.3 on 2022-11-17 21:48

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_tag_options_remove_tag_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main_image',
            field=models.ImageField(upload_to=base.models.post_directory_path),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to=base.models.content_directory_path),
        ),
    ]
